name: Build Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull cis547/cis547-base:latest

    - name: Run Analysis in Docker
      run: |
        sudo apt-get update
        sudo apt install -y clang-format
        docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) cis547/cis547-base:latest \
        bash -c "export LD_LIBRARY_PATH=/opt/mirtk/lib:${LD_LIBRARY_PATH} && \
        rm -rf build && mkdir build && cd build && \
        cmake .. && \
        python3 ../run_all.py"
        find . -path ./build -prune -o \( -name '*.cpp' -o -name '*.h' \) -print | xargs clang-format -style=LLVM -i 
        git config user.email "kdiggs0618@gmail.com"
        git config user.name "Kevin-TD"
        git add .
        git commit -m "Apply clang-format changes"
        git push

    - name: Check Make Exit Status
      run: echo $?

