name: Build Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull cis547/cis547-base:latest
    
    - name: Install Clang Format
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod u+x llvm.sh
        sudo ./llvm.sh 17
        clang-format -version
    
    - name: Check Code Formatting
      run: |
        find . -path ./build -prune -o \( -name '*.cpp' -o -name '*.h' \) -print | xargs clang-format --dry-run -Werror --style=LLVM

    - name: Run Analysis in Docker
      run: |
        docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) cis547/cis547-base:latest \
        bash -c "export LD_LIBRARY_PATH=/opt/mirtk/lib:${LD_LIBRARY_PATH} && \
        rm -rf build && mkdir build && cd build && \
        cmake .. && \
        python3 ../run_all.py"

    - name: Check Make Exit Status
      run: echo $?

