name: Build Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull cis547/cis547-base:latest
    
    - name: Install Artistic Style Formatter
      run: |
        sudo apt-get update
        sudo apt update
        sudo apt install -y astyle
        sudo apt install python3-pip
        pip3 install autopep8
        autopep8 --version
    
    - name: Check Code Formatting
      run: |
        python3 check_formatting.py

    - name: Run Analysis in Docker
      run: |
        docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) cis547/cis547-base:latest \
        bash -c "export LD_LIBRARY_PATH=/opt/mirtk/lib:${LD_LIBRARY_PATH} && \
        rm -rf build && mkdir build && cd build && \
        cmake .. && \
        python3 ../run_all.py"

    - name: Check Make Exit Status
      run: echo $?
