name: Build Analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull cis547/cis547-base:latest

    - name: Run Analysis in Docker
      run: |
        apt-get update
        apt install -y clang-format
        docker run -v $(pwd):/$(basename $(pwd)) -w /$(basename $(pwd)) cis547/cis547-base:latest \
        bash -c "export LD_LIBRARY_PATH=/opt/mirtk/lib:${LD_LIBRARY_PATH} && \
        rm -rf build && mkdir build && cd build && \
        cmake .. && \
        python3 ../run_all.py"
        find . -name '*.cpp' -o -name '*.h' | xargs clang-format -style=LLVM -i 

    - name: Check Make Exit Status
      run: echo $?

